### ISSUE TITLE
installation via pip fails - dependency conflict

### ISSUE THREAD

**Issue by ScDor** [Barmaley13/BarcodeCapture#1]
Hey,
I tried pip-installing barcap in a fresh, empty venv, but got the following errors:

```
Collecting barcap
  Using cached barcap-0.2.7.tar.gz (632 kB)
  Using cached barcap-0.2.6.tar.gz (631 kB)
  Using cached barcap-0.2.5.tar.gz (631 kB)
  Using cached barcap-0.2.4.tar.gz (631 kB)
  Using cached barcap-0.2.2.tar.gz (631 kB)
  Using cached barcap-0.2.1.tar.gz (631 kB)
  Using cached barcap-0.1.12.tar.gz (628 kB)
  Using cached barcap-0.1.11.tar.gz (628 kB)
  Using cached barcap-0.1.10.tar.gz (627 kB)
  Using cached barcap-0.1.9.tar.gz (626 kB)
  Using cached barcap-0.1.8.tar.gz (625 kB)
  Using cached barcap-0.1.7.tar.gz (625 kB)
  Using cached barcap-0.1.6.tar.gz (624 kB)
  Using cached barcap-0.1.5.tar.gz (624 kB)

The conflict is caused by:
    barcap 0.2.7 depends on opencv-python==4.1.1.26
    barcap 0.2.6 depends on opencv-python==4.1.1.26
    barcap 0.2.5 depends on opencv-python==4.1.1.26
    barcap 0.2.4 depends on opencv-python==4.1.1.26
    barcap 0.2.2 depends on opencv-python==4.1.1.26
    barcap 0.2.1 depends on opencv-python==4.1.1.26
    barcap 0.1.12 depends on opencv-python==4.1.1.26
    barcap 0.1.11 depends on opencv-python==4.1.1.26
    barcap 0.1.10 depends on opencv-python==4.1.1.26
    barcap 0.1.9 depends on opencv-python==4.1.1.26
    barcap 0.1.8 depends on opencv-python==4.1.1.26
    barcap 0.1.7 depends on opencv-python==4.1.1.26

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict


    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\IdeaProjects\aaa\venv1\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-b2q2qxm_\\barcap_3fe8305d452d470c94dedc21195f9a6c\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-b2q2qxm_\\barcap_3fe8305d452d470c94dedc21195f9a6c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-4n8grmza'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-b2q2qxm_\barcap_3fe8305d452d470c94dedc21195f9a6c\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-b2q2qxm_\barcap_3fe8305d452d470c94dedc21195f9a6c\setup.py", line 40, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5a/4a/2a5d983d32a9ac753b9dc8171500dc872d3bf386c1b790092921205a1e79/barcap-0.1.6.tar.gz#sha256=1b23b215202bb647a94779fa26c5771179935de6b0b5c71a4086c7f68e28e222 (from https://pypi.org/simple/barcap/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\IdeaProjects\aaa\venv1\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-b2q2qxm_\\barcap_25512587850944519bc7a5f3c576464d\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-b2q2qxm_\\barcap_25512587850944519bc7a5f3c576464d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-httgymj5'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-b2q2qxm_\barcap_25512587850944519bc7a5f3c576464d\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-b2q2qxm_\barcap_25512587850944519bc7a5f3c576464d\setup.py", line 8, in <module>
        from barcap import __version__
      File "C:\Users\User\AppData\Local\Temp\pip-install-b2q2qxm_\barcap_25512587850944519bc7a5f3c576464d\barcap\__init__.py", line 6, in <module>
        from .capture import BarcodeCapture
      File "C:\Users\User\AppData\Local\Temp\pip-install-b2q2qxm_\barcap_25512587850944519bc7a5f3c576464d\barcap\capture.py", line 14, in <module>
        import cv2
    ModuleNotFoundError: No module named 'cv2'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a7/6b/50f01d152591389b872d1c3ff186ab454ba3439d4f85e0891e6f93be595d/barcap-0.1.5.tar.gz#sha256=f0c40e26e71f06853059fcc0b05385317055af03bed4d5b09c646a66e5af65bf (from https://pypi.org/simple/barcap/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install barcap==0.1.10, barcap==0.1.11, barcap==0.1.12, barcap==0.1.7, barcap==0.1.8, barcap==0.1.9, barcap==0.2.1, barcap==0.2.2, barcap==0.2.4, barcap==0.2.5, barcap==0.2.6 and barcap==0.2.7 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Thanks for making the project, I'd appreciate your assistance

**Comment by Barmaley13** [comment]
I tried fixing the problem. Can you try this and see what happens?

```
pip cache purge
pip install barcap
```

Let me know if that works or not.
Thank you
